# Generated by Django 5.0.3 on 2024-03-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_tipo_rename_tipo_permiso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tipo'),
        ),
    ]
