# Generated by Django 5.0.4 on 2024-05-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_remove_proyecto_recursos_remove_tarea_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotarea',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.rolusuarioproyecto'),
        ),
    ]
