# Generated by Django 5.0.4 on 2024-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_usuario_groups_usuario_user_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolpermiso',
            name='idPermiso',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='idRol',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolPermiso',
        ),
    ]
