# Generated by Django 5.0.4 on 2024-05-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_remove_rolpermiso_idpermiso_remove_rolpermiso_idrol_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idPermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.rol')),
            ],
        ),
    ]
