# Generated by Django 5.0.4 on 2024-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_remove_rol_permisos_rolpermiso'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
