# Generated by Django 5.0.4 on 2024-05-10 13:08
from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def crear_permisos(apps, schema_editor):
    Proyecto = apps.get_model('API', 'Proyecto')
    content_type = ContentType.objects.get_for_model(Proyecto)

    permisos_creador = [
        Permission.objects.get_or_create(codename='crear_tarea', name='Can create tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_tarea', name='Can edit tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_tarea', name='Can delete tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_tarea', name='Can view tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_proyecto', name='Can edit project', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_proyecto', name='Can delete project', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_proyecto', name='Can view project', content_type=content_type),
        Permission.objects.get_or_create(codename='crear_rolusuarioproyecto', name='Can create RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_rolusuarioproyecto', name='Can edit RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_rolusuarioproyecto', name='Can delete RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_rolusuarioproyecto', name='Can view RolUsuarioProyecto', content_type=content_type),
    ]   

    permisos_moderador = [
        Permission.objects.get_or_create(codename='crear_tarea', name='Can create tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_tarea', name='Can edit tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_tarea', name='Can delete tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_tarea', name='Can view tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_proyecto', name='Can edit project', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_proyecto', name='Can view project', content_type=content_type),
        Permission.objects.get_or_create(codename='crear_rolusuarioproyecto', name='Can create RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_rolusuarioproyecto', name='Can edit RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_rolusuarioproyecto', name='Can delete RolUsuarioProyecto', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_rolusuarioproyecto', name='Can view RolUsuarioProyecto', content_type=content_type),
        ]

    permisos_colaborador = [
        Permission.objects.get_or_create(codename='crear_tarea', name='Can create tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='editar_tarea', name='Can edit tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='eliminar_tarea', name='Can delete tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_tarea', name='Can view tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_proyecto', name='Can view project', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_rolusuarioproyecto', name='Can view RolUsuarioProyecto', content_type=content_type),
    ]

    permisos_visualizador = [
        Permission.objects.get_or_create(codename='ver_tarea', name='Can view tasks', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_proyecto', name='Can view project', content_type=content_type),
        Permission.objects.get_or_create(codename='ver_rolusuarioproyecto', name='Can view RolUsuarioProyecto', content_type=content_type),
    ]  

class Migration(migrations.Migration):
    dependencies = [
        ('API', '0021_rol_permisos'),  # Reemplaza '0001_initial' con el nombre de la migración anterior
    ]

    operations = [
        migrations.RunPython(crear_permisos),
    ]