# Generated by Django 5.0.3 on 2024-03-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=256)),
                ('tamaño', models.BinaryField()),
                ('fechaSubida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=64)),
                ('entidadAfectada', models.IntegerField()),
                ('descripcion', models.CharField(max_length=256)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=256)),
                ('permisos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=512)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estado')),
                ('recursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.proyecto')),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idPermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.permiso')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=512)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estado')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.proyecto')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.prioridad')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recurso')),
                ('idTarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=64)),
                ('contrasenya', models.CharField(max_length=256)),
                ('estado', models.BooleanField()),
                ('datosPersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.persona')),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuarioProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.proyecto')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.rol')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='contribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.usuario'),
        ),
        migrations.CreateModel(
            name='UsuariosRegistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.registro')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idTarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tarea')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.usuario')),
            ],
        ),
    ]
