# Generated by Django 5.0.4 on 2024-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolpermiso',
            name='idPermiso',
        ),
        migrations.AddField(
            model_name='rol',
            name='grupos',
            field=models.ManyToManyField(related_name='roles', to='auth.group'),
        ),
    ]
