# Generated by Django 5.0.3 on 2024-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='permiso',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
