# Generated by Django 5.0.4 on 2024-05-13 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_rolpermiso_idpermiso_rol_grupos'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolusuarioproyecto',
            name='idRol',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='idRol',
        ),
        migrations.RemoveField(
            model_name='rolusuarioproyecto',
            name='idProyecto',
        ),
        migrations.RemoveField(
            model_name='rolusuarioproyecto',
            name='idUsuario',
        ),
        migrations.CreateModel(
            name='GroupUsuarioProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.proyecto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usuariotarea',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.groupusuarioproyecto'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='RolPermiso',
        ),
        migrations.DeleteModel(
            name='RolUsuarioProyecto',
        ),
    ]
