# Generated by Django 5.0.4 on 2024-05-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_rolusuarioproyecto_idrol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
