# Generated by Django 5.0.3 on 2024-03-31 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_registro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
    ]
