# Generated by Django 5.0.3 on 2024-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_usuario_last_login_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenya',
            field=models.CharField(default='', max_length=256),
        ),
    ]
