# Generated by Django 5.0.4 on 2024-05-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='contribuidor',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='link',
        ),
        migrations.AddField(
            model_name='recurso',
            name='url',
            field=models.URLField(default='https://ibb.co/nzFbxGk'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagenPerfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.recurso'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tamaño',
            field=models.PositiveIntegerField(),
        ),
    ]
