# Generated by Django 5.0.4 on 2024-05-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_recurso_contribuidor_remove_recurso_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='url',
            field=models.URLField(default='https://ibb.co/yy6Kbjz'),
        ),
    ]
