# Generated by Django 5.0.4 on 2024-05-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_recurso_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagenPerfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.recurso'),
        ),
    ]
