# Generated by Django 5.0.4 on 2024-05-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_usuario_imagenperfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='idProyecto',
            new_name='proyecto',
        ),
    ]
