# Generated by Django 5.0.4 on 2024-05-26 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_rename_idproyecto_tarea_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 18, 30, 14, 67286)),
        ),
    ]
