# Generated by Django 5.0.4 on 2024-05-26 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 21, 59, 39, 987619)),
        ),
    ]
