# Generated by Django 5.0.3 on 2024-03-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='recursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.recurso'),
        ),
    ]
