# Generated by Django 5.0.3 on 2024-03-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_proyecto_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='recursos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.recurso'),
        ),
    ]
