# Generated by Django 5.0.4 on 2024-05-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_registro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
    ]
